spring:
  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  h2:
    console:
      path: /h2-console
      enabled: true